Update introduction
SovereignCloudStack/gx-credential-generator pull request #105
Opened 2024-08-23 09:27 UTC by anjastrunk

closes #62

2024-08-31 16:41 UTC, markus-hentsch requested changes

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +gx-credential generator outputs the following Gaia-X Credentials for a CSP in order to be Gaia-X compliant
```suggestion
gx-credential-generator outputs the following Gaia-X Credentials for a CSP in order to be Gaia-X compliant
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Besides the Gaia-X Credentials of CSP of OpenStack cloud, with are required by Gaia-X, the follwing Gaia-X Credentials will be created:
```suggestion
Besides the Gaia-X Credentials of a CSP of an OpenStack cloud, which are required by Gaia-X, the following Gaia-X Credentials will be created:
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +To discover cloud properties, gx-credential generator requires access to OpenStack cloud as normal tenant user.
```suggestion
To discover cloud properties, gx-credential-generator requires access to the OpenStack cloud as normal tenant user.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +gx-credential-generator read the OpenStack catalog to collect
```suggestion
gx-credential-generator queries the OpenStack API to collect
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +### k8s
```suggestion
### Kubernetes (k8s)
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Gaia-X terms and conditions are prompt and you are asked to agree to them. Type 'y' to agree or 'no' to dis-agree.
```suggestion
Gaia-X terms and conditions are displayed and you are prompted to agree to them. Type 'y' to agree or 'n' to disagree.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +**Note**: If you do not agree Gaia-X terms and conditions, process will be aborted and none Gaia-X credential is created.
```suggestion
**Note**: If you do not agree Gaia-X terms and conditions, the process will be aborted and no Gaia-X credential is created.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Gaia-X Credential files are placed in current working directory, be default. To change output directory use parameter `--out-dir`:
```suggestion
Gaia-X Credential files are placed in the current working directory, by default. To change the output directory use the parameter `--out-dir`:
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Running the gx-credential-generator with a specified configuration file path use parameter `--config`:
```suggestion
Running the gx-credential-generator with a specified configuration file path using the parameter `--config`:
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +You can prevent to prompt Gaia-X terms and conditions using option `--auto-sign`. This implies you agree to them:
```suggestion
You can avoid interactive prompt for Gaia-X terms and conditions agreement using the option `--auto-sign`. This implies you agree to them:
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +gx-credential-generator requires access to OpenStack cluster as normal tenant
```suggestion
gx-credential-generator requires access to the OpenStack API as a normal tenant
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
>    Openstack cloud. This is done
```suggestion
  OpenStack cloud. This is done
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +  clouds.yaml is a yaml file containing several cloud configurations. Each configuration is referred by name.
```suggestion
A `clouds.yaml` is a YAML file containing several cloud access configurations. Each configuration is referred to by name.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
>    using [clouds.yaml](https://docs.openstack.org/python-openstackclient/ussuri/configuration/index.html).
```suggestion
  using [clouds.yaml](https://docs.openstack.org/python-openstackclient/latest/configuration/index.html).
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Create Gaia-X Credential for Openstack cloud
```suggestion
Create Gaia-X Credential for an OpenStack cloud
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
```suggestion

(`<os-cloud>` is a placeholder for the name of the desired entry in `clouds.yaml`)

```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +As Gaia-X requires to define a provider for each published service offering, gx-credential-generator creates Gaia-X Credentials for CSP at very run for OpenStack cloud, too.
```suggestion
As Gaia-X requires to define a provider for each published service offering, gx-credential-generator creates Gaia-X Credentials for the CSP at every run for an OpenStack cloud, too.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Each Gaia-X Credential is serialized in [JSON-LD](https://json-ld.org/) and stored in a separate file. Credentials for CSP correspond to the ones generated by command `csp`. Credentials for OpenStack
```suggestion
Each Gaia-X Credential is serialized in [JSON-LD](https://json-ld.org/) and stored in a separate file. Credentials for CSP correspond to the ones generated by the command `csp`. Credentials for OpenStack clouds are prefixed as follows:
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +- so: Mandatory properties for OpenStack cloud
```suggestion
- so: Mandatory properties for the OpenStack cloud
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +- vmso: Detailed description of OpenStack cloud
```suggestion
- vmso: Detailed description of the OpenStack cloud
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +- cs_so: Compliance Credentials for OpenStack cloud as Gaia-X `ServiceOffering` issued by GXDCH Compliance Service
```suggestion
- cs_so: Compliance Credentials for the OpenStack cloud as Gaia-X `ServiceOffering` issued by GXDCH Compliance Service
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +### K8s
```suggestion
### Kubernetes (k8s)
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +gx-credential-generartor is configured by `config.yaml`. The configuration
```suggestion
gx-credential-generator is configured by `config.yaml`. The configuration
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +If values for mandatory attributes can not be discovered from OpenStack or K8S cluster, default values are taken from configuration.
```suggestion
If values for mandatory attributes cannot be discovered from the OpenStack cloud or Kubernetes cluster, default values are taken from the configuration.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Gaia-X Credential schema dictates mandatory attributes for some class.
```suggestion
The Gaia-X Credential schema dictates mandatory attributes for some classes.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
>  system. Operating systems are referred by name, e.g. for Alpine Linux:
```suggestion
system. Operating systems are referenced by name, e.g. for Alpine Linux:
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +gx-credential-generator creates Gaia-X Credentials, which refer to [W3C Verifiable Credentials](https://www.w3.org/TR/vc-data-model-2.0/). Verifiable Credentials requires a proof, e.g. a digital sign
```suggestion
gx-credential-generator creates Gaia-X Credentials, which refer to [W3C Verifiable Credentials](https://www.w3.org/TR/vc-data-model-2.0/). Verifiable Credentials require a proof, e.g. a digital signature of the credential's issuer. Therefore some settings, e.g. a private key to sign, are required and defined in the section `Credentials` of the configuration file.
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +gx-credential-generator interacts with GXDCH service, e.g. to retreive credential for CSP's legal registration number or to assert compliance. To set GXDCH endpoint use section `gxdch`. For a list of
```suggestion
gx-credential-generator interacts with GXDCH service, e.g. to retreive credential for CSP's legal registration number or to assert compliance. To set the GXDCH endpoints use the options in the section `gxdch`. For a list of available GXSCH endpoints refer to [Gaia-X Framework](https://docs.gaia-x.eu/framework/?tab=clearing-house)
```

2024-08-31 16:41 UTC, markus-hentsch commented on README.md
> +Gaia-X defines several level of compliance, each with a different trust level. gx-credential-generator supports the very basic level, called "Conformity" and is compliant Gaia-X Tagus release.
```suggestion
Gaia-X defines several level of compliance, each with a different trust level. gx-credential-generator supports the very basic level, called "Conformity" and is compliant with the Gaia-X Tagus release.
```

2024-09-03 06:55 UTC, anjastrunk commented
@markus-hentsch Thanks for your carefully review. I see, English grammar and spelling is not one of my strength ;-) I applied your suggestions, please re-review.

2024-09-05 07:48 UTC, markus-hentsch requested changes
Just added some small adjustments that I either missed last time or that have changed again after the wave of commits.

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +Comming soon.
```suggestion
Coming soon.
```

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +Comming soon!
```suggestion
Coming soon!
```

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +Create Gaia-X Credential for CSP without specifying a configuration file. This implies the default path at `/etc/gx-credential-generator/config.yaml`, which must exist:
```suggestion
Create Gaia-X Credential for a CSP without specifying a configuration file. This implies the default path at `/etc/gx-credential-generator/config.yaml`, which must exist:
```

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +- cs_csp: Compliance Credential for CSP as Gaia-X `LegalPerson` issued by GXDCH Compliance Service
```suggestion
- lp: Gaia-X Credential containing the CSP's legal address and headquarter address
- lrn: Gaia-X Credential for the CSP's legal registration number issued by GXDCH Notary Service. gx-credential-generator reaches out to Notary Service by itself.
- tandc: Gaia-X Terms and Conditions signed by the CSP
- vp_csp: Presentation of all Gaia-X Credentials to be sent to GXDCH Compliance Service to assert compliance
- cs_csp: Compliance Credential for the CSP as Gaia-X `LegalPerson` issued by GXDCH Compliance Service
```

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +Each Gaia-X Credential is serialized in [JSON-LD](https://json-ld.org/) and stored in a separate file. Credentials for CSP correspond to the ones generated by the command `csp`. Credentials for OpenS
```suggestion
Each Gaia-X Credential is serialized in [JSON-LD](https://json-ld.org/) and stored in a separate file. Credentials for CSPs correspond to the ones generated by the command `csp`. Credentials for OpenStack clouds are prefixed as follows:
```

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +The command to run gx-credential-generator for OpenStack cloud is similar to the one to run gx-credential-generator for CSP. Also arguments `--config`, `--out-dir` and `--auto-sign` are available and
```suggestion
The command to run gx-credential-generator for OpenStack clouds is similar to the one to run gx-credential-generator for a CSP. The arguments `--config`, `--out-dir` and `--auto-sign` are also available and act like for the CSP command.
```

2024-09-05 07:48 UTC, markus-hentsch commented on README.md
> +gx-credential-generator interacts with GXDCH service, e.g. to retreive credential for CSP's legal registration number or to assert compliance. To set the GXDCH endpoints use the options in the sectio
```suggestion
gx-credential-generator interacts with GXDCH service, e.g. to retrieve a credential for a CSP's legal registration number or to assert compliance. To set the GXDCH endpoints use the options in the section `gxdch`. For a list of available GXSCH endpoints refer to [Gaia-X Framework](https://docs.gaia-x.eu/framework/?tab=clearing-house)
```

2024-09-05 13:34 UTC, anjastrunk commented
@markus-hentsch I applies all your suggestions. Thanks a lot for your contribution.

2024-09-05 15:24 UTC, markus-hentsch requested changes
Had one last look over the rendered version and noticed one heading being on the wrong level. Other than, that looks good now.

2024-09-05 15:24 UTC, markus-hentsch commented on README.md
> +### 1. Create configuration file
```suggestion
#### 1. Create configuration file
```

2024-09-05 17:09 UTC, anjastrunk commented
> Had one last look over the rendered version and noticed one heading being on the wrong level. Other than, that looks good now.

Done.

2024-09-10 16:26 UTC, markus-hentsch approved these changes
This looks good to me now. Thanks for the adjustments!

2024-09-12 06:11 UTC, merged