Generate GX conformant credentials for VM Images
SovereignCloudStack/gx-credential-generator pull request #75
Opened 2024-02-29 12:38 UTC by anjastrunk

Duplicate #69 to sign commits.

2024-03-06 10:29 UTC, martinmo reviewed
I reviewed your PR and left some suggestions inline. However, I did not yet try the tool with an OpenStack cloud and plan to do this later.

As a general remark: there are a lot of commented out code lines which I think should be removed. You can always restore old code from the Git history, if necessary.

Some of the new dependencies in `requirements.txt` are not up-to-date anymore.

2024-03-06 10:29 UTC, martinmo commented on README.md
> +`copyrigthowner`, `license` and `resourcePolicy` are mandatory attributes for VM Images and their operating systems. As these values are not accessible from OpenStack cloud, default values are used.
```suggestion
`copyright owner`, `license` and `resource policy` are mandatory attributes for VM Images and their operating systems. As these values are not accessible from OpenStack cloud, default values are used. The values for operating system are defined in section `operating system` with one section for each operating system. Operating systems are refered by name, e.g. for Alpine Linux. 
```

are the attributes according to the examples and `config/config.yaml`

2024-03-06 10:29 UTC, martinmo commented on README.md
> +By default, generator uses operating system values for VM Image as well. I.e. by default, VM Image and operating system have the same values for `copyrigthOwner`, `license` and `resourcePolicy`. Prov
```suggestion
By default, generator uses operating system values for VM Image as well. I.e. by default, VM Image and operating system have the same values for `copyright owner`, `license` and `resource policy`. Providers are able to change values for each VM image, individually. Therefore, the section `own images` in `cloud resources` exists. To set individual values for a specific VM image, add a new section, started by image's name (as defined in OpenStack cloud) to configuration file. The following example defines ìndividual values for `copyright owner`, `license` and `resource policy` for VM image called `AlmaLinux 8`.
```

2024-03-06 10:29 UTC, martinmo commented on README.md
> +          - https://www.abc.org
Is ABC just an arbitrary term/example? If so `example.com` or `example.org` should be used instead of `abc`.

2024-03-06 10:58 UTC, martinmo commented
One more remark: I noticed that the original issues #66 and #67 contain a lot of useful information which could be part of the docs (e.g., design/implementation decisions and information about the mapping from SCS to GX). They were helpful for me to understand the context of this PR and in my opinion it would be a pity if they are hidden in the (soon to be closed) GitHub issues.

2024-03-14 13:24 UTC, anjastrunk commented on requirements.txt
> +rdflib==7.0.0
You are right. I created an issue for you ;-) See https://github.com/SovereignCloudStack/gx-credential-generator/issues/79

2024-03-14 13:36 UTC, anjastrunk commented
@martinmo Please review my changes and approve PR.

2024-03-18 12:08 UTC, mbuechse reviewed
This is some impressive reorganization.
I have mostly minor remarks, but it would be good to address them nonetheless.

2024-03-18 12:08 UTC, mbuechse commented on tests/common.py
> +class OpenstackTestcase(unittest.TestCase):
I'm not familiar with `unittest`. So I'm curious to know the response to this remark.

2024-03-18 12:08 UTC, mbuechse commented on tests/gaia-x.shacl.ttl
> +@prefix gx: <http://w3id.org/gaia-x/gx-trust-framework/> .
What is the source of this? Should we really include a copy of it here, or just provide some shell script that downloads it automatically? We should at least provide some context for the provenance.

2024-03-18 12:08 UTC, mbuechse commented on tests/test_vm_image_discovery.py
> +def _get_gx_images():
I'm inclined to turn these functions into constants. I there any reason for not using constants here? Maybe because the constructed objects are actually mutated somewhere? It would be nice to state this reasoning in a comment.

2024-03-18 12:08 UTC, mbuechse commented on tests/test_vm_image_discovery.py
> +
```suggestion
```

2024-03-18 12:08 UTC, mbuechse commented on tests/test_vm_image_discovery.py
> +            shacl_graph="tests/gaia-x.shacl.ttl",
I don't know if this path will work on Windows, but that is just a side remark.
My actual point is that this relative path indicates that this script be run from the directory above `tests`. This is good to know. Do we have some docs regarding the running of the tests? Should we use `tox` or something (I'm not familiar with tox, maybe @martinmo?)

2024-03-18 14:03 UTC, martinmo commented
@anjastrunk was the merge of the other PR #67 into this PR intentional (fe1b9a7)?

2024-03-18 14:08 UTC, anjastrunk commented
> @anjastrunk was the merge of the other PR #67 into this PR intentional ([fe1b9a7](https://github.com/SovereignCloudStack/gx-credential-generator/commit/fe1b9a7be305c66489520d8a027b38c91ebb8b1b))?

No, it was not.

2024-03-18 14:12 UTC, martinmo commented on tests/test_vm_image_discovery.py
> +            shacl_graph="tests/gaia-x.shacl.ttl",
Good point, I would recommend an absolute path derived from the script path, no matter which test tool is in use. 

The idiom I like to use for this purpose is:

```python
from pathlib import Path

HERE = Path(__file__)

shacl_graph = str(Path(HERE, "gaia-x.shacl.ttl"))
```

(Conversion to `str` is needed because I suspect that `validate(…)` doesn't understand [`PathLike` objects](https://docs.python.org/3.8/library/os.html#os.PathLike).)

> Should we use tox or something (I'm not familiar with tox, maybe @martinmo?)

`tox` would only be useful if we need to orchestrate tests with multiple Python versions.

2024-03-18 14:36 UTC, martinmo commented on README.md
> +`copyrigthowner`, `license` and `resourcePolicy` are mandatory attributes for VM Images and their operating systems. As these values are not accessible from OpenStack cloud, default values are used.
This is still not resolved. The suggestion was not applied. Suggested change:

```suggestion
`copyright owner`, `license` and `resource policy` are mandatory attributes for VM Images and their operating systems. As these values are not accessible from OpenStack cloud, default values are used. The values for operating system are defined in section `operating system` with one section for each operating system. Operating systems are refered by name, e.g. for Alpine Linux. 
```

2024-03-18 14:53 UTC, martinmo reviewed
I reviewed again and only found some minor things :+1:

Some of the earlier suggestions have been marked as resolved but the suggestions have not been applied (these are separate steps in the GitHub UI).

In the "Docker" section they are some examples which I don't agree with, but the section has not been changed with this PR, so I'll create a separate issue for that.

2024-03-18 14:53 UTC, martinmo commented on README.md
> +[//]: <> (- File System:
These `[//]:` strings don't seem right.

2024-03-18 14:53 UTC, martinmo commented on README.md
> +simple SD validator script. Visit the `sd` directory and try to validate your
The suggestion was not applied.

2024-03-18 14:53 UTC, martinmo commented on README.md
> +
The folder `sd/` doesn't exist anymore.

2024-03-18 14:53 UTC, martinmo commented on README.md
> +   ```)
The `[//]:` strings don't seem to be right.

2024-03-18 14:53 UTC, martinmo commented on cli.py
> +#!/usr/bin/env python3
This script should be made executable (`chmod +x`).

2024-03-18 14:56 UTC, martinmo commented on README.md
> +### K88
```suggestion
### K8s
```

2024-03-18 14:57 UTC, martinmo commented on README.md
>     ./gx-sd-generator.py k8s
```suggestion
   ./gx-cred-generator.py k8s
```

2024-03-19 11:01 UTC, mbuechse commented on generator/common/json_ld.py
> +            pass
This doesn't seem to have been addressed (you put a comment into the function above this one)

2024-03-19 11:01 UTC, mbuechse commented on generator/common/json_ld.py
> +                # skip emtpy values
This change is gone somehow.

2024-03-19 11:02 UTC, mbuechse commented on generator/common/json_ld.py
> +    @rtype: dict
this change is gone, but immaterial anyway

2024-03-19 11:02 UTC, mbuechse commented on config/config.yaml
> +#cloud resources:
this change is gone

2024-03-19 11:03 UTC, mbuechse commented on README.md
> +
Has this been addressed? I still think `./sd/validate.py` doesn't exist any more.

2024-03-19 11:04 UTC, mbuechse commented on README.md
> +GX Credential schema allows to describe cloud resources, such VM images, in a fine granular manner, by using attribute `aggregationOf`. This attribute refers a list of GX credentials either as [DID](
this change has gone

2024-03-19 11:04 UTC, mbuechse commented on README.md
> +By default, generator uses operating system values for VM Image as well. I.e. by default, VM Image and operating system have the same values for `copyrigthOwner`, `license` and `resourcePolicy`. Prov
this change seems to have gone as well

2024-03-19 11:05 UTC, mbuechse commented on README.md
> +Tool for creating [Gaia-X Crecentials](https://gitlab.com/gaia-x/technical-committee/architecture-document/-/blob/master/architecture_document/gx_conceptual_model.md#gaia-x-credentials), previously k
This change has gone

2024-03-20 14:13 UTC, anjastrunk commented
@mbuechse @martinmo I improved code quality according to your feedback. Please review again.

2024-03-20 15:25 UTC, mbuechse approved these changes
Minor things. Most notable: I don't know how the EnumDefinitionImpl constructor works -- does it accept objects of the enum class in question, or does it only accept str? In the latter case, in a few instances `.text` should be added.

In some instances, I was wondering whether a value could be `None` or the empty string etc. It would be good to convey this information to the reader by making the code as explicit as possible; see my individual remarks.

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.hw_watchdog_action.lower(), WatchDogActions.disabled
Same question: do we need `WatchDogActions.disabled.text` here?

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +            return VMDiskType("RAW")
even better (again, **provided that disk_format can be None**)

```suggestion
        if os_image.disk_format is None:
            return VMDiskType(VMDiskType.RAW.text)
        return VMDiskType(
            DISK_LOOKUP.get(os_image.disk_format.lower(), VMDiskType.RAW.text)
        )
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +            return False
```suggestion
        return os_image.properties and os_image.properties.get("hw_pmu", False)
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +            return False
```suggestion
        return bool(os_image.is_hw_vif_multiqueue_enabled)
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +                        os_image.hash_algo.lower(), ChecksumAlgorithm.other
Again: do we need `ChecksumAlgorithm.other.text` here?

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +        return RNGTypes("None")
What about `os_image.hw_rng_model`?

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +        return license_list
```suggestion
        return [
            URI(lic) if lic.startswith("http") else lic
            for lic in licenses
        ]
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +            return os_image.name
```suggestion
        return os_image.name or None
```
but the `or None` is only necessary if the `os_image.name` can indeed be an empty string!

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +        return False
```suggestion
        return os_image.properties and os_image.properties.get("licenseIncluded", False)
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +            return os_image.properties["patchlevel"]
```suggestion
        return os_image.properties and os_image.properties.get("patchlevel", False)
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +            return os_image.properties["internal_version"]
```suggestion
        return os_image.properties and os_image.properties.get("internal_version", False)
```

2024-03-20 15:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +                HYPER_LOOKUP.get(os_image.hypervisor_type.lower(), HypervisorType.other)
Do we need `HypervisorType.other.text` here?

2024-03-20 15:26 UTC, mbuechse commented
@anjastrunk And one addendum to my review: it seems that your formatter (black?) is set to some very narrow line width, maybe 80 characters. That is hard to read. Maybe you can set it to 110 characters or so.

2024-03-20 16:03 UTC, martinmo commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.properties["hw_firmware_type"].lower(), FirmType.other
@anjastrunk I agree with @mbuechse: `FirmType(<some str>)` won't work and results in an incomplete object:

```
$ python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from generator.common.gx_schema import FirmType
>>> FirmType("other")
(text='other')
>>> FirmType("other").text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martinmorgenstern/workspace/gx-credential-generator/.venv/lib/python3.10/site-packages/jsonasobj2/_jsonobj.py", line 160, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'FirmType' object has no attribute 'text'
```

This is the case for *all* classes that subclass `EnumDefinitionImpl`.

2024-03-20 16:04 UTC, martinmo commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.properties["hw_firmware_type"].lower(), FirmType.other
And `FirmType(FirmType.other)` has the same issue.

2024-03-20 16:20 UTC, martinmo requested changes
As @mbuechse has suspected, every place where the constructor of an `EnumDefinitionImpl` subclass is used is currently broken.

For instance, `VMDiskType("RAW")` should be replaced with `VMDiskType.RAW` and so on. If this is not possible because the string is not known until runtime, you can use `getattr(…)`: `getattr(VMDiskType, type_str, VMDiskType.RAW)`.

2024-03-20 16:25 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.properties["hw_firmware_type"].lower(), FirmType.other
There must be a canonical way to convert from string to the enum type? But in this case, we should put the correct objects into the lookup already.

2024-03-20 16:34 UTC, martinmo commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.properties["hw_firmware_type"].lower(), FirmType.other
For "ordinary" enums from the stdlib, you can use `EnumType[item_name]`, however `EnumDefinitionImpl` is something custom and the only way I see is to use `getattr(…)` (see [my comment below](https://github.com/SovereignCloudStack/gx-credential-generator/pull/75#pullrequestreview-1949408190)).

2024-03-20 16:42 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.properties["hw_firmware_type"].lower(), FirmType.other
Fortunately, we can just skip the strings altogether and put the enum values into the lookups.

2024-03-20 21:01 UTC, anjastrunk commented
> As @mbuechse has suspected, every place where the constructor of an `EnumDefinitionImpl` subclass is used is currently broken.
> 
> For instance, `VMDiskType("RAW")` should be replaced with `VMDiskType.RAW` and so on. If this is not possible because the string is not known until runtime, you can use `getattr(…)`: `getattr(VMDiskType, type_str, VMDiskType.RAW)`.

This is not correct. Constructor of every `EnumDefinitionImpl` is used in a right way. I used it several times throughout my tests. 

@martinmo Your assumption is wrong: `VMDiskType("RAW")`, `VMDiskType(VMDiskType.RAW)`  as well as `VMDiskType(VMDiskType.RAW.text)` construct an object of class `VMDiskType`, which is a subclass of `EnumDefinitionImpl`. `EnumDefinitionImpl` and does not have an attribute called `text`. Only `PermissibleValue` has `text` as an attribute. If you want to get text of `VMDiskType`, you have to call `VMDiskType.code.text`

```mermaid
classDiagram
EnumDefinitionImpl <|-- VMDiskType
EnumDefinitionImpl --> PermissibleValue:code

class PermissibleValue{
    text: str
}
```
Calling `VMDiskType.RAW`, creates an object of class `PermissibleValue`, which is not requested, as an instance of class `VMDiskType` is required.

```
>>> from generator.common.gx_schema import VMDiskType
>>> type(VMDiskType('RAW')).__name__
'VMDiskType'
>>> type(VMDiskType(VMDiskType.RAW)).__name__
'VMDiskType'
>>> type(VMDiskType(VMDiskType.RAW.text)).__name__
'VMDiskType'
>>> type(VMDiskType.RAW).__name__
'PermissibleValue'
>>> VMDiskType('RAW').code.text
'RAW'
>>> 

```

2024-03-20 21:04 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.properties["hw_firmware_type"].lower(), FirmType.other
Constructor are used in a right way, see https://github.com/SovereignCloudStack/gx-credential-generator/pull/75#issuecomment-2010631152.

I agree with using enum values in lookup, although it doesn't make a difference. It's just consemtics.

2024-03-20 21:04 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +                    os_image.hw_watchdog_action.lower(), WatchDogActions.disabled
`WatchDogActions.disabled` and `WatchDogActions.disabled.text` is similar.

2024-03-20 21:20 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +        if os_image.disk_format:
It is, `disk_format` can be `None`.

2024-03-21 09:26 UTC, martinmo commented
> @martinmo Your assumption is wrong: `VMDiskType("RAW")`, `VMDiskType(VMDiskType.RAW)` as well as `VMDiskType(VMDiskType.RAW.text)` construct an object of class `VMDiskType`, which is a subclass of `EnumDefinitionImpl`. `EnumDefinitionImpl` does not have an attribute called `text`. Only `PermissibleValue` has `text` as an attribute. If you want to get text of `VMDiskType`, you have to call `VMDiskType.code.text`

You're right, thanks for the clarification, @anjastrunk! I am sorry and take back my comment.

For me it was confusing that the enum member is not of the enum type (like it is with Python stdlib enums) and that `VMDiskType("RAW")` has a misleading `repr` of `(text='RAW')`, which made me think it has a `text` attribute. E.g.,

```
>>> from generator.common.gx_schema import VMDiskType
>>> VMDiskType("RAW")
(text='RAW')
```

but

``` 
>>> VMDiskType("RAW").text
AttributeError: 'VMDiskType' object has no attribute 'text'
```

2024-03-21 09:33 UTC, mbuechse commented
Confusing indeed.

2024-03-21 09:35 UTC, martinmo approved these changes
LGTM, but can you please check the mandatory attributes section `README.md` again. There is still a typo in the attributes, somehow the suggestion was again not applied:

* `copyrigthowner` (t and h switched and missing space), should be `copyright owner` as in the YAML.
* `resourcePolicy` (P should be lower case and missing space), should be `resource policy` as in the YAML.

(Or maybe my understanding here is wrong: I think the section talks about the keys in the YAML file.)

2024-03-22 06:22 UTC, anjastrunk commented on .github/workflows/python-app.yml
> +    - uses: actions/checkout@v3
Good point. Thanks,

2024-03-22 06:22 UTC, anjastrunk commented on config/config.yaml
> +        - https://www.abc.org
You are right.

2024-03-22 06:23 UTC, anjastrunk commented on tests/common.py
> +class TestConnection:
Good point. Thanks,

2024-03-22 06:24 UTC, anjastrunk commented on tests/common.py
> +class OpenstackTestcase(unittest.TestCase):
These are methods to check test results. Maybe name is a bit confusing. I renamed them to `assert_...`, similar to built-in assert methods of unittest library.

2024-03-22 06:24 UTC, anjastrunk commented on .github/workflows/python-app.yml
> +        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
Good point. Thanks,

2024-03-22 06:24 UTC, anjastrunk commented on README_old.md
> +# Depracted - see README.md for up-to-date information
Good point. Thanks,.

2024-03-22 06:25 UTC, anjastrunk commented on README.md
> +`copyrigthowner`, `license` and `resourcePolicy` are mandatory attributes for VM Images and their operating systems. As these values are not accessible from OpenStack cloud, default values are used.
These attributes are proper names from Gaia-x ontology and must be written as one word.

2024-03-22 06:26 UTC, anjastrunk commented on README.md
> +By default, generator uses operating system values for VM Image as well. I.e. by default, VM Image and operating system have the same values for `copyrigthOwner`, `license` and `resourcePolicy`. Prov
See https://github.com/SovereignCloudStack/gx-credential-generator/pull/75#discussion_r1535106369

2024-03-22 06:28 UTC, anjastrunk commented on README.md
> +This then should be output as GX compliant credential in JSON-LD for the Gaia-X catalogue.
Done

2024-03-22 06:30 UTC, anjastrunk commented on README.md
> +- public VM Images
Yes documentation is work in progress and will be updated in #62.

Mark them as "work in progress" seems to be a good mid-term solution.

2024-03-22 06:32 UTC, anjastrunk commented on README.md
> +`copyrigthowner`, `license` and `resourcePolicy` are mandatory attributes for VM Images and their operating systems. As these values are not accessible from OpenStack cloud, default values are used.
Done.

2024-03-22 06:32 UTC, anjastrunk commented on README.md
> +Similar to mandatory attributes, GX Credential Schemas supports optional attributes, whose values can not be retrieved from OpenStack cloud. These values can be set in configuration file in section `
Done.

2024-03-22 06:36 UTC, anjastrunk commented on tests/gaia-x.shacl.ttl
> +@prefix gx: <http://w3id.org/gaia-x/gx-trust-framework/> .
I needed them for unit tests and you are right and you are right. We shouldn't have a copy of SHACL shapes in our repository. Instead, shapes should be downloaded from original source. BTW, I found a way to get rid of shacl shape completely, be re-organizing/re-writing tests-.

2024-03-22 06:39 UTC, anjastrunk commented on README.md
> +[//]: <> (- File System:
My WYSIWYG editor uses `[//]` to mark comments, bit GitHub unfortunately not. I removed them.

2024-03-22 06:40 UTC, anjastrunk commented on README.md
> +simple SD validator script. Visit the `sd` directory and try to validate your
I did this manually.

2024-03-22 06:41 UTC, anjastrunk commented on README.md
> +
You are right. I removed this paragraph.

2024-03-22 06:41 UTC, anjastrunk commented on README.md
> +   ```)
See https://github.com/SovereignCloudStack/gx-credential-generator/pull/75#discussion_r1535115661

2024-03-22 06:41 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +            return False
Good hint. Thanks.

2024-03-22 06:44 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +            return os_image.name
`os_image.name` can be an empty string, indeed!

2024-03-22 06:47 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +            return os_image.properties["patchlevel"]
Good hint, thanks.

2024-03-22 06:47 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +            return os_image.properties["internal_version"]
Good hint, thanks.

2024-03-22 06:56 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +                HYPER_LOOKUP.get(os_image.hypervisor_type.lower(), HypervisorType.other)
`HypervisorType.other.text` and `HypervisorType.other` are similar in this context.

2024-03-22 06:58 UTC, anjastrunk commented
@martinmo @martinmo Thanks for our tremendous feedback and very carefully review. It helped my a lot to improve code quality and documentation.

2024-03-22 07:00 UTC, anjastrunk commented
> LGTM, but can you please check the mandatory attributes section `README.md` again. There is still a typo in the attributes, somehow the suggestion was again not applied:
> 
>     * `copyrigthowner` (t and h switched and missing space), should be `copyright owner` as in the YAML.
> 
>     * `resourcePolicy` (P should be lower case and missing space), should be `resource policy` as in the YAML.
> 
> 
> (Or maybe my understanding here is wrong: I think the section talks about the keys in the YAML file.)

Indeed. I changed it.

2024-03-22 13:53 UTC, merged