Build CI/CD Pipeline for GX Credential Generator
SovereignCloudStack/gx-credential-generator pull request #84
Opened 2024-04-09 07:50 UTC by anjastrunk

close #76

2024-04-17 09:48 UTC, martinmo requested changes
Looks good! I have found a few places which could be improved (maybe), please have a look at my comments.

FYI, the link-validator and build-python-app workflows have warnings wrt to deprecated actions (checkout and setup-python).

2024-04-17 09:48 UTC, martinmo commented on k8s-discovery.py
> +        print(my_kube, file=open(ofile, "a", encoding="UTF-8"))
```suggestion
        print(my_kube, file=open(ofile, mode="a", encoding="UTF-8"))
```

2024-04-17 09:48 UTC, martinmo commented on .github/workflows/build-python-app.yml
> +          coverage report -m
When pytest is used, I think it is better to use the `pytest-cov` plugin for code coverage (it also uses `coverage` under the hood). See https://github.com/SovereignCloudStack/standards/tree/main/Tests#unit-and-regression-tests (Option C) for example.

I also recommend to put the configuration (flags such as `--omit`) into a `.coveragerc` file, so you have easy access to the same configuration if you test and measure coverage locally.

2024-04-17 09:48 UTC, martinmo commented on gx-cred-generator.py
> +        print(output(mycloud, myk8s), file=open(file_name, "a", encoding="UTF-8"))
```suggestion
        print(output(mycloud, myk8s), file=open(file_name, mode="a", encoding="UTF-8"))
```

2024-04-17 09:48 UTC, martinmo commented on tests/test_cli.py
> +                get_absolute_path("tests/data/empty_credential.json"), "r"
```suggestion
                get_absolute_path("tests/data/empty_credential.json"), mode="r"
```

2024-04-17 12:44 UTC, anjastrunk commented
@martinmo Thanks for your review. I replaced `coverage` with `pytest-cov` and bumped up github action to `actions/checkout@v4`

2024-04-17 12:59 UTC, martinmo requested changes

2024-04-17 12:59 UTC, martinmo commented on tests/coverage.xml
This file shouldn't be in version control and should be ignored.

2024-04-19 15:22 UTC, martinmo requested changes
In the last review I forgot to ask: is the append mode in some of the `open(…)` calls intentional, instead of `mode="w"`? I know it is not actually the scope of this PR, but because of the reformatting I noticed these in the diffs.

It is not part of the diff, but can you change the hidden `.flake8` to just ignore `E501` (line length) as follows:

```
[flake8]
ignore = E501
```

The other warnings should remain active and the code conforms to them, at the moment.

Apart from that I only found some minor nitpicks.

2024-04-19 15:22 UTC, martinmo commented on .coveragerc
> +omit = *_test.py,tests/*,generator/common/gx_schema.py,*__init__*,generator/vendor/*
```suggestion
omit = 
  tests/*
  generator/common/gx_schema.py
  generator/vendor/*
```

`coverage` supports this multi line format, which is easier to read. Also, some of the entries are unnecessary:

* there are no `*_test.py` files in the repo and
* there is only a single `__init__.py` file in the already omitted `generator/vendor/`. (If you really intend to exclude all future `__init__.py` files, I suggest to use the more specific `*/__init__.py` instead.)

2024-04-19 15:22 UTC, martinmo commented on .github/workflows/lint-python-syntax.yml
> +          python-version: '3.x'
```suggestion
          python-version: '3.10'
```

2024-04-19 15:22 UTC, martinmo commented on .github/workflows/lint-python-syntax.yml
> +          python-version: '3.x'
```suggestion
          python-version: '3.10'
```

2024-04-19 15:22 UTC, martinmo commented on flake8
> +
This file is a duplicate of the hidden `.flake8` file with the same contents and can be removed.

2024-04-22 07:05 UTC, anjastrunk commented on flake8
> +
Removed. See 97a3f73dfe9cf12024038ce16547b82819d454ca

2024-04-22 07:13 UTC, anjastrunk commented
> In the last review I forgot to ask: is the append mode in some of the `open(…)` calls intentional, instead of `mode="w"`? I know it is not actually the scope of this PR, but because of the reformatting I noticed these in the diffs.

I have no idea, if append mode is intended. As I didn't write this code, I will leave it as it is. BTW: Old code will be removed/refactored in later PRs.

2024-04-23 14:39 UTC, martinmo commented on .flake8
> +ignore = E501,E226,E251,E221,E501
```suggestion
ignore = E501
```

is enough and the lint still passes with these settings (see https://github.com/SovereignCloudStack/gx-credential-generator/pull/84#pullrequestreview-2011643696)

2024-04-23 14:40 UTC, martinmo requested changes
Just one suggestion for the `.flake8` file, otherwise okay! :+1:

2024-04-24 07:10 UTC, martinmo approved these changes

2024-04-25 06:37 UTC, merged