Move code coverage to own github workflow
SovereignCloudStack/gx-credential-generator pull request #90
Opened 2024-04-26 07:22 UTC by anjastrunk

Move code coverage to  separate GitHub workflow to add code coverage overview to PR, always.

2024-04-26 08:45 UTC, martinmo requested changes
I propose to stick with one workflow, `build-python-app.yml`, to avoid duplication:

If I understand it correctly, you added the new workflow because you want to have the PR comment to be created even if the coverage is below the threshold?

If this is this case, you can set [`jobs.<job-id>.strategy.fail-fast`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to `false` like this:

```yaml
jobs:
  build-python-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    # ...
```

(The default is `true` which is the reason the steps after `CodeCoverageSummary` aren't executed it the threshold isn't met.)

Last, I propose you add `.gx-credentials/` to `.gitignore` so the credentials will not be committed unintentionally.

2024-04-26 08:45 UTC, martinmo commented on coveragerc
> +output = coverage.xml
This file should be merged with the hidden `.coveragerc` file. I think the non-hidden file isn't read by coverage (for example, the `show_missing` switch doesn't seem to be active when I run `coverage report` without the `-m` switch locally).

2024-04-26 08:45 UTC, martinmo commented on .github/workflows/build-python-app.yml
> +
The job name and actions do not align: `cat …` doesn't add a threshold, it only prints the markdown file to stdout.

2024-04-29 09:24 UTC, anjastrunk commented on coveragerc
> +output = coverage.xml
Yes, you are right. I merged `coveragerc` in `.coveragerc`

2024-04-29 09:25 UTC, anjastrunk commented on .github/workflows/build-python-app.yml
> +
Removed job step `add threshold to coverage.md`

2024-04-29 10:48 UTC, martinmo commented
> If this is this case, you can set [`jobs.<job-id>.strategy.fail-fast`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to `false` like this:
> 
> ```yaml
> jobs:
>   build-python-app:
>     runs-on: ubuntu-latest
>     strategy:
>       fail-fast: false
>     steps:
>     # ...
> ```

@anjastrunk in addition to disabling `fail-fast`, one needs to add `!cancelled()` to the `if` clause of the steps following the code coverage step, see [bca4ffd](https://github.com/SovereignCloudStack/gx-credential-generator/pull/91/commits/bca4ffd509e3ecdb1ac9ad45e3bf3e157b2a7dc3) of the test PR https://github.com/SovereignCloudStack/gx-credential-generator/pull/91. Sorry for the incomplete initial suggestion!

2024-04-29 10:49 UTC, martinmo commented on .github/workflows/build-python-app.yml
> +        experimental: [false]
```suggestion
```

2024-04-29 12:20 UTC, anjastrunk commented
> > If this is this case, you can set [`jobs.<job-id>.strategy.fail-fast`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to `false` like this:
> > ```yaml
> > jobs:
> >   build-python-app:
> >     runs-on: ubuntu-latest
> >     strategy:
> >       fail-fast: false
> >     steps:
> >     # ...
> > ```
> 
> @anjastrunk in addition to disabling `fail-fast`, one needs to add `!cancelled()` to the `if` clause of the steps following the code coverage step, see [bca4ffd](https://github.com/SovereignCloudStack/gx-credential-generator/pull/91/commits/bca4ffd509e3ecdb1ac9ad45e3bf3e157b2a7dc3) of the test PR #91. Sorry for the incomplete initial suggestion!

@martinmo Many thanks for your support. Now it works as expected.

2024-04-30 08:15 UTC, martinmo approved these changes
The changes are good to go in my opinion! Only the title of the PR should be changed to reflect what was actually done.

2024-04-30 10:40 UTC, merged