Add GXDCH services
SovereignCloudStack/gx-credential-generator pull request #96
Opened 2024-06-10 13:26 UTC by anjastrunk

relates to #70

2024-08-15 14:01 UTC, markus-hentsch commented
I started reviewing and wanted to some practical tests for the OpenStack part using a DevStack of mine.

The instructions in the README are unlcear. In short, it says to do the following:

```sh
cd gx-credential-generator

python3 cli.py openstack <os-cloud>
```

However, `cli.py` is located in the "generator" subdirectory but even when navigating to it, it fails:

```sh
cd generator/
python3 cli.py openstack devstack
```

```
Traceback (most recent call last):
  File "<redacted>/gx-credential-generator/generator/cli.py", line 23, in <module>
    import generator.common.const as const
ModuleNotFoundError: No module named 'generator'
```

@anjastrunk what is the correct way of invoking the generator?

2024-08-15 14:29 UTC, mbuechse commented
@markus-hentsch If I may... I think you need to run

```text
python3 -m generator.cli openstack devstack
```

from the root of the repo.

2024-08-16 07:55 UTC, anjastrunk commented
> @markus-hentsch If I may... I think you need to run
> 
> ```
> python3 -m generator.cli openstack devstack
> ```
> 
> from the root of the repo.

@mbuechse is right. You have to run and should add you own configuration file.

 ```
python3 -m generator.cli openstack devstack --config <path-to-your-config>
```
If you omit `--config` parameter, configuration file is taken from `config/config.yaml` sub-directory. I will send you a sample configuration file via PM. 


@markus-hentsch You are right. Documentation has to be improved. I will do this within a separate PR.

2024-08-16 10:05 UTC, mbuechse commented
@anjastrunk Will you send me the file as well? Do you plan to get code coverage for `discovery` back to at least 90? (Then I might wait with the review...)

2024-08-16 10:45 UTC, markus-hentsch commented
> 
> @mbuechse is right. You have to run and should add you own configuration file.
> 
> ```
> python3 -m generator.cli openstack devstack --config <path-to-your-config>
> ```
> 
> If you omit `--config` parameter, configuration file is taken from `config/config.yaml` sub-directory. I will send you a sample configuration file via PM.
> 
> @markus-hentsch You are right. Documentation has to be improved. I will do this within a separate PR.

Thanks. I used the new command now and it starts execution.

I have encountered two issues while testing:

## Incompatibility with non-compliant images

In my DevStack there are images that are not SCS-compliant and lack some of the expected metadata, leading to an error:

```
  File ".../gx-credential-generator/generator/discovery/openstack/vm_images_discovery.py", line 290, in _get_operation_system
    if os_image.os_distro.lower() == "arch":
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

I don't think we can expect every image visible to the user to have all the metadata.

## Missing output processing and VP

When executing the generator, it seems to print a dump of all generated VCs simply concatenated together.
Piping the output to a file with `python3 ... > output.json` is not really helping as the file also includes status output of the tool at the top:

```
"tandc"
"lrn"
"lp"
"cs"
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/jws-2020/v1",
    "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
  ],
  "type": "VerifiableCredential",
...
```

... and the individual VCs are not really separated. My suggestion would be:

1. only print status messages to stdout, not the JSON (the VCs are far too long, depending on the terminal used, you might not be able to scroll back far enough)
2. write each VC into an individual `.json` file in an output folder
3. additionally write a Verifiable Presentation (VP) `.json` that includes all VCs like in [this template](https://gitlab.com/gaia-x/lab/workshops/gaia-x-101/-/blob/master/templates/vp.j2?ref_type=heads)

I think this would improve user experience greatly as the VP could be directly used at the GXDCH Compliance API.

2024-08-16 10:46 UTC, markus-hentsch requested changes
See https://github.com/SovereignCloudStack/gx-credential-generator/pull/96#issuecomment-2293277651

2024-08-16 10:49 UTC, mbuechse commented
> In my DevStack there are images that are not SCS-compliant

I'm not even sure if this is a matter of compliance. If your image is very specific (not a general purpose OS image), it could be reasonable to omit the `os_distro` property.

2024-08-20 07:47 UTC, anjastrunk commented
> ## Incompatibility with non-compliant images
> 
> In my DevStack there are images that are not SCS-compliant and lack some of the expected metadata, leading to an error:
> 
> ```
>   File ".../gx-credential-generator/generator/discovery/openstack/vm_images_discovery.py", line 290, in _get_operation_system
>     if os_image.os_distro.lower() == "arch":
>        ^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'lower'
> ```
> 
> I don't think we can expect every image visible to the user to have all the metadata.

Thanks for bringing this up. You are completely right, we can not assume presence of any optional property. I will change this and look for other occurrence of such type of properties,

2024-08-20 13:45 UTC, anjastrunk commented
@markus-hentsch @mbuechse I increased code coverage and fixed the issues in https://github.com/SovereignCloudStack/gx-credential-generator/pull/96#issuecomment-2293277651. Please do a re-review. Thanks

2024-08-20 14:23 UTC, mbuechse reviewed
First round of review done. So far, mostly very minor things.

2024-08-20 14:23 UTC, mbuechse commented on generator/cli.py
> +    print('Create VC of type "gx:VirtualMachineServiceOffering"...', end='')
Use of print seems smelly to me. Maybe at least print to stderr?

2024-08-20 14:23 UTC, mbuechse commented on generator/cli.py
> +    so_vc['credentialSubject'] = {
See above about print and dict literal.

2024-08-20 14:23 UTC, mbuechse commented on generator/cli.py
> +        "gx:termsAndConditions": list(),
```suggestion
        "gx:termsAndConditions": [
            {'gx:URL': s_tac.url, 'gx:hash': s_tac.hash}
            for s_tac in vm_offering.serviceOfferingTermsAndConditions
        ],
```

2024-08-20 14:23 UTC, mbuechse commented on generator/cli.py
> +            'gx:hash': s_tac.hash})
```suggestion
```

if suggestion above is being followed

2024-08-20 14:23 UTC, mbuechse commented on generator/cli.py
> +        out_dir = os.getcwd()
I think this is equivalent to `out_dir = '.'`, and this could be the default value for the `click` command-line option (as well as `_print_vcs`), so this strange special case can be dropped (explicit is better than implicit)

2024-08-20 14:23 UTC, mbuechse commented on generator/common/const.py
> +CONFIG_TaC = "terms-and-conditions"
```suggestion
CONFIG_T_AND_C = "terms-and-conditions"
```

the lowercase character would break convention for constants, and it's called `T_AND_C` already in the `CONFIG_IAAS` case

2024-08-20 14:23 UTC, mbuechse commented on generator/common/credentials.py
> +    return json.dumps(vp)
not sure about the json.dumps though... it violates the single responsibility/separation of concerns principle.

2024-08-20 14:23 UTC, mbuechse commented on generator/common/json_ld.py
> +        json_ld["id"] = "ex:" + obj.gx_id.replace(" ", "")
Just curius: why is the `@` being dropped? Isn't it part of json-ld?

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/csp_generator.py
> +        print('Create and sign VC of type "gx:GaiaXTermsAndConditions" for CSP...', end='')
I might tolerate `print` in a module called `cli`, but I wouldn't tolerate print here.

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/csp_generator.py
> +                return
This should be a separate method. The parameter `auto_sign` should be dropped from `generate` as well as this method. I could imagine the following:

- add instance variable `tand_signed` to constructor, default False (but True would be permissible)
- the separate method sets this instance variable to True once the user has agreed
- this method right here throws an exception if the instance variable is False

Not sure how costly `self.registry.get_gx_tandc()` is. Maybe the value could be cached.

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/csp_generator.py
> +        tandc_vc = dict()
Please use a dict literal.

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/csp_generator.py
> +        lp_vc = dict()
please use a dict literal

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/gxdch_services.py
> +            resp.raise_for_status()
```suggestion
        resp.raise_for_status()
        return resp.text
```

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/gxdch_services.py
> +        self.api = api
I would suggest a better name instead of `api`, see above

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/gxdch_services.py
> +        body['gx:vatID'] = csp[const.CONFIG_CSP_REG_NUMBER][const.CONFIG_CSP_VAT_ID]
please use dict literal

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/gxdch_services.py
> +            resp.raise_for_status()
```suggestion
        resp.raise_for_status()
        return resp.json()
```

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/gxdch_services.py
> +        self.api = api
see above

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/gxdch_services.py
> +            resp.raise_for_status()
see above

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/openstack/openstack_discovery.py
> +                "Service offerings terms and conditions MUST not be empty. Please check config.yaml. There MUST be at least on entry."
```suggestion
                "Service offerings terms and conditions MUST not be empty. Please check config.yaml. There MUST be at least one entry."
```

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/openstack/openstack_discovery.py
>          if len(service_tac) == 0:
```suggestion
        if not service_tac:
```

2024-08-20 14:23 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +    "unicore32": "RISC-V"
```suggestion
    "unicore32": "RISC-V",
```

Why was the trailing comma removed?

2024-08-21 08:38 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +    "unicore32": "RISC-V"
Because it's the last element of dict and comma is not required.

2024-08-21 08:40 UTC, anjastrunk commented on generator/cli.py
> +    print('Create VC of type "gx:VirtualMachineServiceOffering"...', end='')
As these are logging information, stderr would not fit, IMO.

2024-08-21 08:41 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +    "unicore32": "RISC-V"
https://peps.python.org/pep-0008/#when-to-use-trailing-commas

> When trailing commas are redundant, they are often helpful when a version control system is used, when a list of values, arguments or imported items is expected to be extended over time. The pattern is to put each value (etc.) on a line by itself, always adding a trailing comma, and add the close parenthesis/bracket/brace on the next line.

2024-08-21 08:42 UTC, mbuechse commented on generator/cli.py
> +    print('Create VC of type "gx:VirtualMachineServiceOffering"...', end='')
To the contrary: logging information is something you wouldn't usually want to pipe to another tool, and correspondingly, the Python `logging` module by default uses `stderr`.

2024-08-21 08:57 UTC, anjastrunk commented on generator/cli.py
> +        "gx:termsAndConditions": list(),
Done.

2024-08-21 08:57 UTC, anjastrunk commented on generator/cli.py
> +            'gx:hash': s_tac.hash})
Done.

2024-08-21 09:28 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +        self.api = api
Done.

2024-08-21 09:28 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +            resp.raise_for_status()
Done.

2024-08-23 14:12 UTC, markus-hentsch requested changes
I like the rework with separate files and the `--out-dir` option.

However, the produced VP JSONs aren't valid JSON due to wrong conversion. See my code comment.

2024-08-23 14:12 UTC, markus-hentsch commented on generator/cli.py
> +                vc_file.write(json.dumps(vcs[key], indent=2))
I think this needs a little bit of refactoring. If this is used as is, the generated VP JSONs look like this:

```json
"{\"@context\": \"https://www.w3.org/2018/credentials/v1\", \"type\": \"VerifiablePresentation\", \"verifiableCredential\": [{\"@context\":  ...
```
(not a valid JSON, everything is wrapped in `"` and all inner `"` are escaped)

This is because `vcs[key]` is a string in case of the VPs (originating from `credentials.py:convert_to_vp()` whereas it is a dict for the VCs. The correct output can be produced with:

```diff
- vc_file.write(json.dumps(jvcs[key], indent=2))
+ vc_file.write(json.dumps(json.loads(vcs[key]), indent=2))
```

... but that seems bad style. I think the value types of the `vcs` dict should be consistent instead and converted where needed at the other places.

The same goes for the "vp_so" code branch below.

2024-08-23 18:12 UTC, mbuechse commented on generator/cli.py
> +        conn = o_stack.connect(
okay

2024-08-23 18:13 UTC, mbuechse commented on generator/discovery/openstack/vm_images_discovery.py
> +    "unicore32": "RISC-V"
How is this resolved?

2024-08-23 18:15 UTC, mbuechse commented on generator/cli.py
> +                vc_file.write(json.dumps(vcs[key], indent=2))
That's funny, because I already critized the `json.dumps` in `credentials.py:convert_to_vp` here: https://github.com/SovereignCloudStack/gx-credential-generator/pull/96/files#r1723385860
It seemed smelly, and now we have the evidence.

2024-08-23 18:16 UTC, mbuechse reviewed
There are multiple unresolved conversations from my previous review. Maybe you overlooked them because Github wants you to click on "Load more ..."

2024-08-26 06:05 UTC, anjastrunk commented on generator/discovery/openstack/vm_images_discovery.py
> +    "unicore32": "RISC-V"
Done.

2024-08-26 06:37 UTC, anjastrunk commented on generator/cli.py
> +# import openstack as os
I can't not apply this suggestion, as I already have an identifier called `openstack`, which will overwrite import.

2024-08-26 06:39 UTC, anjastrunk commented on generator/cli.py
> +    print('Create VC of type "gx:VirtualMachineServiceOffering"...', end='')
I favor of time, I will introduce logging in an other MR.

2024-08-26 06:42 UTC, anjastrunk commented on generator/common/const.py
> +CONFIG_TaC = "terms-and-conditions"
You are right. I changed it.

2024-08-26 06:43 UTC, anjastrunk commented on generator/common/json_ld.py
> +        json_ld["id"] = "ex:" + obj.gx_id.replace(" ", "")
It's because Gaia-X prefers `id` instead of `@id`

2024-08-26 07:17 UTC, anjastrunk commented on generator/discovery/csp_generator.py
> +        print('Create and sign VC of type "gx:GaiaXTermsAndConditions" for CSP...', end='')
As I said, in favor of time, I will introduce a logging concept in an other MR.

2024-08-26 07:21 UTC, anjastrunk commented on generator/cli.py
> +    so_vc['credentialSubject'] = {
Done.

2024-08-26 07:22 UTC, anjastrunk commented on generator/cli.py
> +        out_dir = os.getcwd()
Good hint. Thanks. I changed it.

2024-08-26 07:26 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +            resp.raise_for_status()
Done.

2024-08-26 07:27 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +            resp.raise_for_status()
Done.

2024-08-26 07:28 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +        self.api = api
Done.

2024-08-26 07:29 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +        body['gx:vatID'] = csp[const.CONFIG_CSP_REG_NUMBER][const.CONFIG_CSP_VAT_ID]
Done.

2024-08-26 07:29 UTC, anjastrunk commented on generator/discovery/gxdch_services.py
> +        self.api = api
Done.

2024-08-26 07:29 UTC, anjastrunk commented on generator/discovery/csp_generator.py
> +        lp_vc = dict()
Done.

2024-08-26 07:30 UTC, anjastrunk commented on generator/discovery/csp_generator.py
> +        tandc_vc = dict()
Done.

2024-08-26 11:21 UTC, anjastrunk commented on generator/discovery/csp_generator.py
> +                return
I agree. Asking for permission to sign terms and condition should be part of `cli.py` not `csp_generator.py`. I changed this.

2024-08-26 11:23 UTC, anjastrunk commented on generator/cli.py
> +                vc_file.write(json.dumps(vcs[key], indent=2))
See https://github.com/SovereignCloudStack/gx-credential-generator/pull/96#discussion_r1730806805

2024-08-26 12:45 UTC, anjastrunk commented
@markus-hentsch @mbuechse All good things come in threes... Third round of review ;-)

2024-08-27 08:24 UTC, markus-hentsch commented on generator/common/credentials.py
> +def convert_to_vp(creds: List[dict]) -> str:
```suggestion
def convert_to_vp(creds: List[dict]) -> dict:
```

2024-08-27 09:46 UTC, markus-hentsch requested changes
I noticed that when generating VCs you are referencing different JSON files for credential id and subject id, for example:

- credential id: `<url>/tandc.json`
- credential subject id: `<url>/tandc_subject.json`

I don't think that hosting separate file copies makes sense here. I assume you did that to represent the same asset while keeping identifiers unique (as required by the RFC).

In Gaia-X examples[^1], they often use an anchor (e.g. `#subject`) within the same JSON in order to keep the identifiers unique while still referencing the same file. The anchors do not need to be resolvable. See the corresponding section of my blog post paragraph[^2] for some more context.

I think we should use anchors here as well and reference a single file for each asset only to keep things simple and prevent file copies getting out of sync.
I added suggestions to adjust the affected code parts.

[^1]: https://gitlab.com/gaia-x/lab/workshops/gaia-x-101/-/blob/e0b01980eead64c0a20fec4643659b4c9d9f3331/gaia-x-101.ipynb#L116

[^2]: https://github.com/SovereignCloudStack/website/blob/381d6ff38d33e4b8697cde010c6f74108aae0f93/_i18n/en/_posts/blog/2024-06-05-demystifying-gaia-x-credentials.md?plain=1#L222-L248

2024-08-27 09:46 UTC, markus-hentsch commented on generator/cli.py
> +            "id": cred_settings[const.CONFIG_CRED_BASE_CRED_URL] + "/so_cs.json",  # iaas['did'],
```suggestion
            "id": cred_settings[const.CONFIG_CRED_BASE_CRED_URL] + "/so.json#subject",  # iaas['did'],
```

2024-08-27 09:46 UTC, markus-hentsch commented on generator/discovery/csp_generator.py
> +            cred_subject_id=self.cred_base_url + "/lrn_cs.json")
```suggestion
            cred_subject_id=self.cred_base_url + "/lrn.json#subject")
```

2024-08-27 09:46 UTC, markus-hentsch commented on generator/discovery/csp_generator.py
> +                "id": self.cred_base_url + "/tandc_cs.json"
```suggestion
                "id": self.cred_base_url + "/tandc.json#subject"
```

2024-08-27 09:46 UTC, markus-hentsch commented on generator/discovery/csp_generator.py
> +                "id": self.cred_base_url + "/legal_person_cs.json",
```suggestion
                "id": self.cred_base_url + "/legal_person.json#subject",
```

2024-08-27 09:46 UTC, markus-hentsch commented on tests/test_csp_generator.py
> +            cred_subject_id=self.conf.get_value([const.CONFIG_CRED, const.CONFIG_CRED_BASE_CRED_URL]) + "/lrn_cs.json"
```suggestion
            cred_subject_id=self.conf.get_value([const.CONFIG_CRED, const.CONFIG_CRED_BASE_CRED_URL]) + "/lrn.json#subject"
```

2024-08-27 09:46 UTC, markus-hentsch commented on tests/test_csp_generator.py
> +        self.assertEqual(self.conf.get_value([const.CONFIG_CRED, const.CONFIG_CRED_BASE_CRED_URL]) + "/tandc_cs.json",
```suggestion
        self.assertEqual(self.conf.get_value([const.CONFIG_CRED, const.CONFIG_CRED_BASE_CRED_URL]) + "/tandc.json#subject",
```

2024-08-27 09:46 UTC, markus-hentsch commented on tests/test_csp_generator.py
> +            self.conf.get_value([const.CONFIG_CRED, const.CONFIG_CRED_BASE_CRED_URL]) + "/legal_person_cs.json",
```suggestion
            self.conf.get_value([const.CONFIG_CRED, const.CONFIG_CRED_BASE_CRED_URL]) + "/legal_person.json#subject",
```

2024-08-27 12:15 UTC, markus-hentsch reviewed
Last round of suggestions: some minor remaining `CPS` typo fixes.

2024-08-27 12:15 UTC, markus-hentsch commented on generator/common/const.py
> +CONFIG_CSP = "CPS"
```suggestion
CONFIG_CSP = "CSP"
```

2024-08-27 12:15 UTC, markus-hentsch commented on config/config.yaml
>  CPS:
```suggestion
CSP:
```

2024-08-27 12:15 UTC, markus-hentsch commented on generator/common/const.py
> +# CPS configuration keys
```suggestion
# CSP configuration keys
```

2024-08-27 12:15 UTC, markus-hentsch commented on generator/cli.py
> +    """Generate Gaia-X Credential for CPS."""
```suggestion
    """Generate Gaia-X Credential for CSP."""
```

2024-08-27 12:15 UTC, markus-hentsch commented on generator/cli.py
> +    """Generates Gaia-X Credentials for CPS and kubernetes."""
```suggestion
    """Generates Gaia-X Credentials for CSP and Kubernetes."""
```

2024-08-27 15:06 UTC, markus-hentsch commented
With the latest commits I can attest that the produced VCs and VPs for the OpenStack side of things are valid as I was able to successfully:

- verify the proof on all generated VCs
- submit each generated VP to the Gaia-X Compliance API and receive a valid compliance VC in turn

Note that I have only been able to verify the OpenStack ServiceOffering generation due to the lack of a suitable Kubernetes cluster.

---

For the record, these are the scripts I used for the VC and VP validations mentioned above:

<details>
  <summary>VC verification script (click to expand ...)</summary>
  
  ```py
  """Verify proof signature of local credential

  Provide full path to a Verifiable Credential (VC) as the only argument.
  The VC must contain a "proof" property.
  """

  import sys
  import json
  from utils import (
      verify_credential, get_verification_cert_url_from_did
  )

  local_cred_path = sys.argv[1]

  print(f"Verifying '{local_cred_path}' ...")
  with open(local_cred_path, 'r') as f:
      vc_as_json = json.loads(f.read())

  verification_cert_url = get_verification_cert_url_from_did(
      vc_as_json.get("proof").get("verificationMethod")
  )
  verify_credential(json.dumps(vc_as_json), verification_cert_url)
  print("Verified.")
  ```
  
</details>

<details>
  <summary>VP compliance script (click to expand ...)</summary>
  
  ```python
  """Issue a local Verifiable Presentation for compliance

  Provide full path to a Verifiable Presentation (VP) as the only argument.
  Will send the VP to the Gaia-X Compliance API and receive a Verifiable
  Credential (VC) attesting the VP's compliance. The received VC's proof
  is then additionally verified at the end of the script.
  """

  import sys
  import json
  import requests
  from utils import (
      verify_credential, get_verification_cert_url_from_did
  )

  GXDCH_COMPLIANCE_API_URL = \
      "https://compliance.lab.gaia-x.eu/v1-staging/api/credential-offers"

  local_pres_path = sys.argv[1]

  print(f"Submitting '{local_pres_path}' ...")
  with open(local_pres_path, 'r') as f:
      vp_as_json = json.loads(f.read())

  compliance_response = requests.post(
      GXDCH_COMPLIANCE_API_URL,
      json.dumps(vp_as_json)
  )

  if compliance_response.status_code == 201:
      compliance = compliance_response.json()
  else:
      raise Exception(
          "Unable to submit to compliance: " +
          compliance_response.text
      )

  print("Verifying received VC proof ...")

  # verify the proof received by the Compliance API
  verification_cert_url = get_verification_cert_url_from_did(
      compliance.get("proof").get("verificationMethod")
  )
  verify_credential(json.dumps(compliance), verification_cert_url)
  print("Verified.")
  print()
  print("Received valid compliance VC:")
  print(json.dumps(compliance, indent=2, sort_keys=True))
  ```
  
</details>

<details>
  <summary>utils.py library with utility functions (click to expand ...)</summary>
  
  ```python
  import os
  import requests
  import json
  from jwcrypto import jwk, jws
  from utils import sha256_normalized_vc, normalize


  def resolve_did(did_ref):
      # did_ref example:
      #   did:web:compliance.lab.gaia-x.eu:v1-staging#X509-JWK2020

      # DID Resolver
      if did_ref.count(':') == 2:
          _, _, fqdn = did_ref.split(':', 2)
          if '#' in fqdn:
              fqdn, _ = fqdn.split('#')
          did_url = f"https://{fqdn}/.well-known/did.json"
      else:
          _, _, fqdn, version = did_ref.split(':', 3)
          if '#' in version:
              version, _ = version.split('#')
          did_url = f"https://{fqdn}/{version}/.well-known/did.json"
      # ---

      did_response = requests.get(did_url)
      did_json = did_response.json()

      return did_json


  def get_verification_cert_url_from_did(did_ref):
      if not did_ref.startswith("did:web:"):
          raise Exception(
              f"Not a supported DID to retrieve cert: '{did_ref}'"
          )
      did_json = resolve_did(did_ref)
      x5u_url = did_json.get("verificationMethod")[0]\
                        .get("publicKeyJwk")\
                        .get("x5u")
      return x5u_url


  def verify_credential(credential_json_str, cert_url):

      verifiable_credential = json.loads(credential_json_str)

      # Retrieve the registry certificate which serves as the verification
      # public key (JWK) for the JWS later
      reg_cert_response = requests.get(cert_url)
      if reg_cert_response.status_code != 200:
          raise Exception(
              f"Unable to retrieve verification certificate "
              f"from: {cert_url}"
          )
      verification_cert_pem = reg_cert_response.text.encode('UTF-8')
      verification_key = jwk.JWK.from_pem(verification_cert_pem)

      # The proof object is part of the credential response, however
      # it resembles JWS data applicable to the response without the
      # proof object. Hence, we need to strip the proof object from
      # the response.
      proof = verifiable_credential.pop("proof")

      # The remaining structure is the actual credential data that
      # JWS was created for. The signature was applied to its
      # normalized and hashed form, which we need to recreate here
      # in order to verify the signature.
      normalized_credential = normalize(verifiable_credential)
      hashed_credential = sha256_normalized_vc(normalized_credential)

      # Instantiate a JWS object based on the jws attribute of the
      # proof object, which contains a base64 representation of the JWS.
      received_jws_token = jws.JWS()
      received_jws_token.deserialize(proof["jws"])

      # Finally, use the verification key (Gaia X registry public cert)
      # and the hashed credential (which is the JWS' detached payload)
      # in conjunction with the JWS token to verify the credential.
      # This method will throw an exception if verification fails.
      received_jws_token.verify(
          verification_key,
          detached_payload=hashed_credential.hexdigest()
      )
  ```
  
</details>

2024-08-28 08:50 UTC, mbuechse approved these changes
LGTM. Markus has a better grasp of the functionality, so he should approve as well.

2024-08-28 11:57 UTC, markus-hentsch approved these changes
Thanks for the adjustments! I tested the OpenStack part again. LGTM now.

2024-08-29 06:48 UTC, merged